#!/usr/bin/env bash

set -e

mentioned="${1?}"
sender="${2?}"
message="${3?}"

# Escape backslashes
message="${message//\\/\\\\}"

# quote double quotes in the message text
message="${message//\"/\\\"}"

osascript -e "display notification \"$message\" with title \"Mattermost message from $sender\""
