#!/usr/bin/env bash

set -e

mentioned="${1?}"
sender="${2?}"
message="${3?}"

# Sanitize message text and sender: escape backslashes and quote double
# quotes
message="${message//\\/\\\\}"
message="${message//\"/\\\"}"
sender="${sender//\\/\\\\}"
sender="${sender//\"/\\\"}"

osascript -e "display notification \"$message\" with title \"Mattermost message from $sender\""
