#! /usr/bin/env sh

# This is the sample Linux notifier for V2 notifications.
# The notification payload is a JSON object presented to standard input,
# having the fields version, sender, message and mentioned.

json=`cat`
version=`echo $json|jq -Mr .version`
[ "$version" = 2 ] || { echo $0: JSON payload has wrong version; exit 1; }
sender=`echo $json|jq -Mr .sender`
message=`echo $json|jq -M .message`
mentioned=`echo $json|jq -Mr .mentioned`

## THIS IS A TEMPORARY STUB; REWRITE FOR notify-send:
LOG=/home/dlamkins/MATTERHORN/matterhorn/notify.log
echo $sender said $message >> $LOG
